unixorn/fzf-zsh-plugin

fzf-zsh-plugin.plugin.zsh

Update `$MANPATH` so users can `man fzf` or `man tmux`

Update the MANPATH too

---

fzf-zsh-plugin.plugin.zsh

fzf looks for FZF_DEFAULT_OPTS  not ,,,_OPS
another 1 character change man_shrugging:
(probably best to squash this with that last PR I just sent) :
- [x ] All new and existing tests pass.
- [x ] Any scripts added use `#!/usr/bin/env interpreter` instead of potentially platform-specific direct paths (`#!/bin/sh` is an ok exception)
- [x ] Scripts are marked executable
- [ x] Scripts _do not_ have a language file extension unless they are meant to be sourced and not run standalone. No one should have to know if a script was written in bash, python, ruby or whatever. Not including file extensions makes it easier to rewrite the script in another language later without having to change every reference to the previous version.
- [ x] I have confirmed that the link(s) in my PR are valid.
- [ x] …

fix typo in FZF_DEFAULT_OPTS env var

---

fzf-zsh-plugin.plugin.zsh

Correct typo in the added fzf manpath directory
just transpose from /~ to ~/
- [ x ] All new and existing tests pass.
- [ x ] Any scripts added use `#!/usr/bin/env interpreter` instead of potentially platform-specific direct paths (`#!/bin/sh` is an ok exception)
- [ x ] Scripts are marked executable
- [ x ] Scripts _do not_ have a language file extension unless they are meant to be sourced and not run standalone. No one should have to know if a script was written in bash, python, ruby or whatever. Not including file extensions makes it easier to rewrite the script in another language later without having to change every reference to the previous version.
- [ x ] I have confirmed that the link(s) in my PR are valid.
- [ x ] I have read the **CONTRIBUTING** document.
- [ x ] This …

fix manpath

---

bin/fif
fzf-zsh-plugin.plugin.zsh

- Add `fif`
- Use `fd` if installed

Improve settings, use fd when present

---

README.md
bin/fzf-find-edit
bin/fzf-grep-edit
bin/fzf-kill
bin/git-fzf-add
bin/git-fzf-log-browser
bin/git-fzf-pickaxe-browser
bin/git-fzf-reflog-browser
fzf-zsh-plugin.plugin.zsh

- Add `git-fzf-add`, `git-fzf-log-browser`, `git-fzf-pickaxe-browser`, and `git-fzf-reflog-browser` scripts that all use `fzf` to interact with `git`.
- Add `fzf-find-edit` script - uses `fzf` to select a file and calls `$EDITOR` on it
- Add `fzf-kill` - uses `fzf` to pick a process to kill

Add more fzf helpers

---

bin/fzf-find-edit
bin/fzf-grep-edit
fzf-zsh-plugin.plugin.zsh

- Add missing `has()` function to `fzf-find-edit` and `fzf-grep-edit`

Add missing function

---

README.md
bin/chrome-bookmark-browser
bin/chrome-history
bin/d-attach
bin/d-image-rm
bin/d-rm
bin/d-stop-container
bin/tm
bin/tmux-search
bin/vagrant-box-search

Add a bunch of fzf functions
- `chrome-bookmark-browser` - Search Chrome bookmarks, open them using default browser
- `d-attach` - Start a `docker` container and attach to it
- `d-image-rm` - Select `docker` images and remove them
- `d-rm` - Selects `docker` containers to remove
- `d-stop-container` - Select `docker` container to stop
- `tm` - Select/create tmux session
- `tmux-search` - Select tmux sessions
- `vagrant-box-search` - Find a `vagrant` vm and connect via `ssh`

Add a bunch more fzf helper scripts

---

fzf-zsh-plugin.plugin.zsh

Don't install `fzf` in `~` if it's already on the machine

Don't install fzf in ~ if it's already on the machine

---

completions/_fzf
fzf-zsh-plugin.plugin.zsh

- Add tab completion
- Use `function` consistently
- Fix `z` override

Add tab completion for fzf

---

README.md
bin/tm
bin/tmux-kill

Add tmux-kill script

---

README.md
bin/asdf-fzf-install
bin/asdf-fzf-remove
bin/asdf-fzf-uninstall

- Add `asdf-install`, `asdf-uninstall` scripts from wiki
- Add `asdf-remove` as symlink to `asdf-uninstall` so I don't have to remember whether it uses `uninstall` or `remove` to remove language binaries

Add asdf helper scripts from fzf wiki

---

README.md
bin/apt-fzf-search
bin/asdf-fzf-install
bin/asdf-fzf-uninstall
bin/chrome-bookmark-browser
bin/fzf-brew-install
bin/fzf-brew-uninstall
fzf-zsh-plugin.plugin.zsh

- dynamically generate `$FZF_DEFAULT_OPTS` based on what commands are available in `$PATH`
- shellcheck cleanups of `asdf-fzf-*`, `fzf-brew-*`, `chrome-bookmark-browser`

Shellcheck fixes and default opt updates

---

fzf-zsh-plugin.plugin.zsh

Fix "diretory" to "directory" in comment on line 15.
p.s. Please feel to close this PR un-merged and just include the change in your next regular update of consequence; I don't want to clutter your git history with trivialities like this but still figured you'd want everything to read as professionally as the code itself does... :) Thanks for sharing your code!

fix tiny typo

---

README.md

Using the clone command provided in the readme fails:
```bash
git clone git@github.com:unixorn/fzf-zsh-plugin.git fzf-zsh
Cloning into 'fzf-zsh'...
The authenticity of host 'github.com (140.82.121.3)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,140.82.121.3' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```
With `https://github.com/unixorn/fzf-zsh-plugin.git` it works:
```bash
git clone https://github.com/unixorn/fzf-zsh-plugin.git fzf-zsh
Cloning into 'fzf-zsh'...
remote: Enumerating objects: 252, done.
remote: Counting objects: 100% (252/252), done.
remote: …
```

Fix clone command in README.md

---

bin/chrome-history

Wasn't using a unique path to the temporary copy of the history file, make a scratch directory with `mktemp` and put the file there so we don't have a collision if two copies of the script are running simultaneously.

Fix race condition if two chrome-history scripts ran at once

---

fzf-zsh-plugin.plugin.zsh

Fix extra fi :-(

---

README.md

- Change fzf-zsh to fzf-zsh-plugin in Oh-My-ZSH section
- Add git checkout url to manual install section
Closes #28

Update install instructions and TOC

---

README.md

Add link to fzf-pass ZSH plugin

---

fzf-zsh-plugin.plugin.zsh

`fzf` can be installed with `--xdg` which will install it to `$XDG_CONFIG_HOME/fzf`. This plugin doesn't respect that. This PR fixes it.

Support XDG based installation path

---

fzf-zsh-plugin.plugin.zsh

The current command doesn't work for me for some reason. Please verify that this works as I run this in WSL, which itself could be the problem.
Signed-off-by: Patrick Li <patrick@papaq.org>

Fix unable to launch vim via ctrl-e

---

README.md
fzf-zsh-plugin.plugin.zsh

Add `falias` function to search your ZSH aliases.

Add falias function

---

fzf-zsh-plugin.plugin.zsh

I tried to install it by using you plugin but it fails because it doesn't generate the binary file "fzf".
According to the junegunn/fzf repo, in order to install it by using git, you have to execute "install" script after cloning.
Documentation: https://github.com/junegunn/fzf#using-git
These are the options for the installer in case you need:
--help               Show this message
--bin                Download fzf binary only; Do not generate ~/.fzf.{bash,zsh}
--all                Download fzf binary and update configuration files
to enable key bindings and fuzzy completion
--xdg                Generate files under \$XDG_CONFIG_HOME/fzf
--[no-]key-bindings  Enable/disable key bindings (CTRL-T, CTRL-R, ALT-C)
--[no-]completion    Enable/disable fuzzy completion (bash & zsh) …

Install after cloning for getting the binary file

---

bin/fzf-brew-install
bin/fzf-brew-uninstall
bin/fzf-brew-update

Multiple brew commands were missing --preview 'brew info {}'
Adds "--preview 'brew info {}'" argument to:
- bin/ff-brew-install
- bin/fzf-brew-uninstall
- bin/ff-brew-update

Add "brew info" as fzf preview option where missing for homebrew fzf commands

---

README.md

Add link to fzf-tab

---

fzf-zsh-plugin.plugin.zsh

Whenever .zshrc is sourced, the plugin is re-run which causes
PATH to be appended to even when the user has $path set to -U
This commit makes it so that users who don't want -U continue to
get the same behavior, and users with -U get the desired behavior.

Make PATH not append to -U path array

---

README.md

Until https://github.com/zsh-users/antigen/issues/717 gets fixed, the
branch needs to be specified when this is not `master`.
Signed-off-by: Gerard Bosch <gerard.bosch@gmail.com>
Fixes https://github.com/unixorn/fzf-zsh-plugin/issues/54
DOES NOT APPLY FOR THIS CHANGE

Update README installation for Antigen

---

bin/fif

As per the following change it seems `fif` command stopped working: https://github.com/unixorn/fzf-zsh-plugin/commit/0578f7e3dda91ae3997cb8066885305be83274c4#r67236895
This happens at least when `FZF_PREVIEW_WINDOW` is empty, but I have no idea what could/should this variable contain and if the quotes would be strictly necessary in any particular case.
This seems that was changed to make Shellcheck happy.
👇 I think most of the following does not apply for this very small fix attempt. Maybe the tests would? But I don't see where to find or how to run those tests :)

Fix `fif` command

---

README.md
fzf-zsh-plugin.plugin.zsh

By default the preview is hidden but the user can decide how to set the
preview by setting this environment variable. The value will also be
taken by other scripts like `fif`.
Signed-off-by: Gerard Bosch <gerard.bosch@gmail.com>

Extract FZF_PREVIEW_WINDOW to allow customization

---

README.md
bin/d-stop-container
fzf-zsh-plugin.plugin.zsh

Properly formatting the options allow to print them nicely:
```
echo $FZF_DEFAULT_OPTS
```
will print one option per line, all with same indentation.
This makes understanding its value easier.
Here is the comparison before/after:
Signed-off-by: Gerard Bosch <gerard.bosch@gmail.com>

Format FZF_DEFAULT_OPTS value

---

README.md
fzf-settings.zsh
fzf-zsh-plugin.plugin.zsh

Allows user to specify a custom fzf install directory. By default, it is still installed in `~/.fzf`.
My main motivation is that I would prefer to install in `~/.config`. The current support for this is broken, as `fzf-settings.zsh` only sources from `~/.fzf`. In addition, the scripts only installs in `~/.config` when `~/.config/fzf` is present, but this requires users deliberately creating this directory, and no one would know since there is no documentation for this.
As an alternative, I have [another branch](https://github.com/caojoshua/fzf-zsh-plugin/tree/config) where I implemented installing in `~/.config` by default. Not sure if this is a good idea though, because it will change the install locations for current users and may be breaking.

Custom fzf install directory

---

fzf-zsh-plugin.plugin.zsh

Fixes https://github.com/unixorn/fzf-zsh-plugin/issues/52.
The script currently does not install fzf in the home directory if `which fzf` returns true. This is why users are having problems when they have fzf installed globally. This change always installs fzf if the fzf home directory does not exist.

Install fzf if not found in home.

---

README.md

Minor change to README instructions
Other plugins tend to use this format for install, simple 2 steps.

Simplify README.md oh-my-zsh instructions

---

bin/lessfilter-fzf

Stifle warnings in `lesspipe.sh`

Stifle warnings in `lesspipe.sh`

---

bin/fif

When `FZF_PREVIEW_WINDOW` is unset in `fif`, give it a default value.

Fix issue when `FZF_PREVIEW_WINDOW` is unset in `fif`

---

README.md
bin/fzf-vscode

Mark posted a handy script to search files with `rg` and `fzf` and edit them with VS Code.

Add mcarey's vscode helper script

---

README.md

The current implementations clone the entire history of this project.
Now it only clones the last changes, decreasing the size of the directory
https://git-scm.com/docs/git-clone#Documentation/git-clone.txt---depthltdepthgt
Checklist not required

Add `--depth 1` to git clones

---

fzf-zsh-plugin.plugin.zsh

Currently, both the manpath and the fzf manpath is appended to manpath, which quickly makes for long manpath when opening shells. This improves that by only appending the fzf manpath to manpath.
To test old behavior. Setup the plugin in zshrc. type zsh. echo $MANPATH. type zsh, echo $MANPATH. See the variable grow quickly. as it is doubleadded.

Only append to MANPATH

---

fzf-zsh-plugin.plugin.zsh

Since the zoxide init script (`zoxide init zsh`) alias `z` to `__zoxide_z`, but this plugin unset it. 
If zoxide is detected, don't touch the alias of `z`.

Resolve conflict with zoxide

---

README.md

It seems the action `id` was renamed. This fixes the link to use the correct link, so the badge properly appears.

readme: Use correct Megalinter CI badge

---

.github/workflows/mega-linter.yml

actionlint and kics are too pedantic, demote their errors to warnings

Demote some mega-linter errors to warnings

---

README.md
fzf-zsh-plugin.plugin.zsh

Enables users to change FZF color scheme
Adds a `FZF_COLOR_SCHEME` variable in main plugin file with default value.
Closes #91

Added ability to change color scheme

---

README.md
bin/lessfilter-fzf

Replace `exa` by `eza` as exa is unmaintained. The new repository is https://github.com/eza-community/eza

Replace exa by eza as exa is unmaintained

---

fzf-zsh-plugin.plugin.zsh

Only add `FZF_PLUGIN_BIN` to `$PATH` when it isn't already there.
Closes #96

Clean up `PATH` manipulation

---

fzf-zsh-plugin.plugin.zsh

Only install `fzf` when it isn't already in `$PATH`. Fixes #87, #44

Only install `fzf` when it isn't already in `$PATH`

---

fzf-zsh-plugin.plugin.zsh

Update the plugin's `FZF_DEFAULT_COMMAND` per suggestion in #69. The plugin also only sets $FZF_DEFAULT_COMMAND` when it isn't already set so that any custom user settings don't get stepped on by the plugin.
Fixes #69.

Update plugin's `FZF_DEFAULT_COMMAND`

---

fzf-zsh-plugin.plugin.zsh

- Don't assume `bat` is installed for use in previews.
- If it is installed, don't assume is installed as `bat` - it might be installed as `batcat`.

Don't assume `bat` is installed

---

fzf-zsh-plugin.plugin.zsh

Only add `FZF_COMPLETIONS_D` to `fpath` when it is an existing directory.

Update `FZF_COMPLETIONS_D` handling

---

bin/pr-list

Other scripts check for `fzf`:
- https://github.com/unixorn/fzf-zsh-plugin/blob/671291a0dba1971d5c87a0cdc809711a9b7636fa/bin/fzf-git-checkout#L28-L30
- https://github.com/unixorn/fzf-zsh-plugin/blob/671291a0dba1971d5c87a0cdc809711a9b7636fa/bin/fzf-browse-pods#L41
- https://github.com/unixorn/fzf-zsh-plugin/blob/671291a0dba1971d5c87a0cdc809711a9b7636fa/bin/fzf-vscode#L44-L46
But, this one was not checking `fzf` and `jq`, which is rather unique for this script. So, I've updated the deps list.

Check for `jq` and `fzf` in `pr-list` script

---

bin/d-attach

The script `bin/d-attach` defines a function named `da`, but calls function `dattach`, which is not defined. Running the script results in an error message:
```
❯ d-attach                                                      
/Users/jxb2016/.zgenom/sources/unixorn/fzf-zsh-plugin/___/bin/d-attach: line 36: dattach: command not found
```
This update changes the script so that it calls `da`.

`bin/d-attach` defines function `da` but calls function `dattach`

---

bin/d-image-rm

When selecting the images to delete, check if the `tag` of an image is the string `<none>`. If it is, then use the image ID,
otherwise, use `repo:tag` for the name of the image to remove.
When an image ID has multiple tags, removing by just the ID will fail.
E.g.:
```
❯ docker image ls | grep ubuntu
docker.artifactory.homedepot.com/ubuntu                                    18.04                d1a528908992   19 months ago   56.7MB
docker.artifactory.homedepot.com/ubuntu                                    18.10                6b562d43ba8f   5 years ago     60.9MB
docker.artifactory.homedepot.com/ubuntu                                    sid                  6b562d43ba8f   5 years ago     60.9MB
```
```
Error response from daemon: conflict: unable to delete 6b562d43ba8f (must be forced) - …
```

d-image-rm: handle multiple tags for same image

---

bin/chrome-history

Fix the `chrome-history` command which always fails with "No such file or directory" and "no such table: urls" errors when called. The variables `chrome_history` and `open` are not declared inside of the function.
This function is trying to access the chrome_history and open vars that are in outer scope.
The `chrome-history()` function declared `chrome_history` and `open` as local variables, which
shadowed the global variables set earlier in the script. This caused the function to use empty
local variables instead of the properly initialized global ones containing the Chrome history
file path and system-appropriate open command. This caused this error:
```bash
$ chrome-history
cp: : No such file or directory
Error: in prepare, no such table: urls
```
Remove `chrome_history` and `open` …

Fix chrome-history command failing due to variable shadowing

---

fzf-settings.zsh
fzf-zsh-plugin.plugin.zsh

- Remove extra `unset -f _fzf_haz`
Fixes #125, hopefully

Fix #125, hopefully

---

fzf-settings.zsh
fzf-zsh-plugin.plugin.zsh

`_fzf_has()` is getting unset when it shouldn't be. Replace `_fzf_has()` with `(( $+commands[commandname] ))` to hopefully fix #125

Replace `_fzf_has()`
